### ISSUE TITLE
PDERefiner - Dimensions do not match when time_future != 1

### ISSUE THREAD

**Issue by saydemr** [pdearena/pdearena#42]
Hi,

I am trying to reproduce the results for the PDERefiner paper. In the paper, there are experiments regarding how many previous timesteps the model uses as input and in the main experiment the model predicts every 4th step. I assume these coincide with parameters `model.time_history`, `model.time_future` and `model.time_gap` in the [configuration file](https://github.com/pdearena/pdearena/blob/22360a766387c3995220b4a1265a936ab9a81b88/configs/kuramotosivashinsky1d.yaml#L100). Yet, setting anything other than 0 fails with a dimension mismatch error with the convolutions. Could you share at least an insight as to how properly integrate those values to the model?

Thanks.

```
model:
  name: "Unetmod-1d-64"
  max_num_steps: 1000
  activation: "gelu"
  criterion: mse
  lr: 1e-4
  param_conditioning: "scalar_2"
  padding_mode: "circular"
  predict_difference: True
  difference_weight: 0.3
  min_noise_std: 4e-7
  num_refinement_steps: 3
  time_history: 1
  time_future: 4
  time_gap: 1
```
```
Exception has occurred: RuntimeError
Given groups=1, weight of size [64, 5, 3], expected input[3, 2, 258] to have 5 channels, but got 2 channels instead
  File "/mnt/fp/pdearena/pdearena/modules/conditioned/oned_unet.py", line 710, in forward
    x = self.image_proj(x)
  File "/mnt/fp/pdearena/pdearena/models/pderefiner.py", line 142, in train_step
    pred = self.model(x_in, time=k * self.time_multiplier, z=cond)
  File "/mnt/fp/pdearena/pdearena/models/pderefiner.py", line 170, in training_step
    loss, preds, targets = self.train_step(batch)
  File "/mnt/fp/pdearena/scripts/pderefiner_train.py", line 46, in main
    cli.trainer.fit(cli.model, datamodule=cli.datamodule)
  File "/mnt/fp/pdearena/scripts/pderefiner_train.py", line 53, in <module>
    main()
RuntimeError: Given groups=1, weight of size [64, 5, 3], expected input[3, 2, 258] to have 5 channels, but got 2 channels instead```
